# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  # The name used to reference this repository in the checkout step
  - repository: jeremy-training 
    type: github
    endpoint: testconnection1
    name: jeremy-training/bashCalc
# The name used to reference this repository in the checkout step
  - repository: KangsWindowsBatchRepo
    type: github
    endpoint: testconnection1
    name: jeremy-training/winBatch

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

#Muliple Stages with multiple jobs
#Different OS and different github repo
stages:

#First Stage on Ubuntu
- stage: UbuntuQAEnvCheck
  jobs:
  - job: InlineScripts
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    #No Checkout
    - checkout: none
    - script: echo Hello, world!
      displayName: 'Run a one-line script'

    - script: |
        echo Learning is fun, please check below.
        echo See https://www.kavinschool.com/content/
      displayName: 'Run a multi-line script'